# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-134394-616804/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a200tfbg676-2
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv {
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/common/aib_adapt_fifo_mem.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aibadapt/aibadapt_rxchnl/aib_adapt_rx_fifo.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aibadapt/aibadapt_txchnl/aib_adapt_tx_fifo.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aibadapt/aib_adapter.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aibadapt/aibadapt_rxchnl/aib_adapter_rxchnl.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aibadapt/aibadapt_txchnl/aib_adapter_txchnl.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aibadapt/aibadapt_avmm/aib_avalon.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aibadapt/aibadapt_avmm/aib_avalon_adapt_reg.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aibadapt/aibadapt_avmm/aib_avalon_if.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aibadapt/aibadapt_avmm/aib_avalon_io_regs.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aib_top/aib_avmm_glue_logic.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aib_top/aib_avmm_top.v
      /home/mendes/axi4_aib/axi4_aib_tools/rtl/interfaces/axi_if.v
      /home/mendes/axi4_aib/axi4_aib_tools/rtl/full_examples/axi_lite/aib_axi_bridge_master.v
      /home/mendes/axi4_aib/axi4_aib_tools/rtl/full_examples/axi_lite/aib_axi_bridge_slave.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/common/aib_bert_cdc.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aibadapt/aibadapt_rxchnl/aib_bert_chk.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aibadapt/aibadapt_txchnl/aib_bert_gen.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/common/aib_bit_sync.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/common/aib_bscan.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/common/aib_bus_sync.v
      /home/mendes/axi4_aib/axi4_aib_tools/rtl/full_examples/axi_lite/aib_calib_master_fsm.v
      /home/mendes/axi4_aib/axi4_aib_tools/rtl/full_examples/axi_lite/aib_calib_slave_fsm.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aib_fsm/aib_cdr_fsm.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aib_top/aib_channel_n.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/common/aib_clk_div.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/common/aib_clk_div_dcs.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/common/aib_clk_div_rcomp.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/common/aib_clk_div_roffcal.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/common/aib_clk_div_sys.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aib_fsm/aib_dcs_fsm.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aib_top/aib_deskew_logic.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aib_fsm/aib_dfx_mon.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aib_fsm/aib_dll_ctrl_logic.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/common/aib_fifo_and_sel.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/common/aib_fifo_rdata_buf.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/common/aib_fifo_rdata_ored.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aib_fsm/aib_ntl_fsm.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aib_top/aib_phy_top.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/redundancy/aib_redundancy.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/redundancy/aib_redundancy_wrp.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/redundancy/aib_redundancy_wrp_top.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/common/aib_rst_sync.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aibadapt/aibadapt_rxchnl/aib_rx_bert.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aibadapt/aibadapt_rxchnl/aib_rx_dbi.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aibadapt/aibadapt_rxchnl/aib_rx_fifo_wam.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aibadapt/aibadapt_rxchnl/aib_rxfifo_clk_gating.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aibadapt/aibadapt_rxchnl/aib_rxfifo_rd_dpath.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aibadapt/aibadapt_rxchnl/aib_rxfifo_rdata_sel.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aibadapt/aibadapt_sr/aib_sr_fsm.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aibadapt/aibadapt_sr/aib_sr_master.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aibadapt/aibadapt_sr/aib_sr_slave.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aibadapt/aibadapt_txchnl/aib_tx_bert.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aibadapt/aibadapt_txchnl/aib_tx_dbi.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aibadapt/aibadapt_txchnl/aib_txfifo_clk_gating.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aibadapt/aibadapt_txchnl/aib_txfifo_rd_dpath.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/DLL/RX_DLL/aibio_3bit_bin_to_therm.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/DLL/RX_DLL/aibio_4bit_plus1.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/aibio_adc_cbb.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aib_top/aibio_ana_top.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/AUX_CH/aibio_auxch_Schmit_trigger.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/AUX_CH/aibio_auxch_cbb.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/DLL/RX_DLL/aibio_bias_trim.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/DLL/RX_DLL/aibio_cdr_detect.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/aibio_clkdist_inv1_cbb.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/aibio_clkdist_inv2_cbb.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/DLL/aibio_decoder2x4.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/DLL/aibio_decoder3x8.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/DLL/aibio_dll_top.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/aibio_dqs_dcs_cbb.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/DLL/RX_DLL/aibio_half_adder.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/DLL/RX_DLL/aibio_inpclk_select.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/DLL/TX_DLL/aibio_inpclk_select_txdll.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/DLL/aibio_lock_detector.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/DLL/aibio_outclk_mux16x1.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/DLL/aibio_outclk_select.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/DLL/RX_DLL/aibio_pi_codeupdate.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/DLL/RX_DLL/aibio_pi_decode.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/DLL/RX_DLL/aibio_pi_decode_sync.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/DLL/RX_DLL/aibio_pi_mixer_top.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/DLL/RX_DLL/aibio_pi_phsel_halfside.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/DLL/RX_DLL/aibio_pi_phsel_quarter.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/DLL/aibio_piclk_dist.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/DLL/aibio_pimux4x1.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/DLL/RX_DLL/aibio_pioddevn_mixer_top.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/DLL/RX_DLL/aibio_pioddevn_phsel_half.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/DLL/RX_DLL/aibio_pioddevn_top.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/DLL/TX_DLL/aibio_pulsegen_mux2x1.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/DLL/TX_DLL/aibio_pulsegen_mux8x1.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/DLL/TX_DLL/aibio_pulsegen_muxfinal.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/DLL/TX_DLL/aibio_pulsegen_oddevn_halfside.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/DLL/TX_DLL/aibio_pulsegen_phsel_halfside.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/DLL/TX_DLL/aibio_pulsegen_top.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/PVTMON/aibio_pvtmon_3to8dec.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/PVTMON/aibio_pvtmon_cbb.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/PVTMON/aibio_pvtmon_clk_divby2.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/PVTMON/aibio_pvtmon_clkdiv.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/PVTMON/aibio_pvtmon_ctr10b.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/PVTMON/aibio_pvtmon_ctrunit.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/PVTMON/aibio_pvtmon_dig.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/PVTMON/aibio_pvtmon_digview.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/PVTMON/aibio_pvtmon_ndmnn11.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/PVTMON/aibio_pvtmon_oscbank.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/PVTMON/aibio_pvtmon_pdmpp11.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/aibio_rxclk_cbb.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/DLL/RX_DLL/aibio_rxdll_cbb.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/DLL/aibio_se_to_diff.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/DLL/TX_DLL/aibio_txdll_cbb.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/TXRX/aibio_txrx_cbb.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/aibio_vref_cbb.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/dv/emib/aliasv.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/dv/interface/avalon_mm_if.sv
      /home/mendes/axi4_aib/axi4_aib_tools/rtl/axi_mm/axi_mm_master_concat.sv
      /home/mendes/axi4_aib/axi4_aib_tools/rtl/axi_mm/axi_mm_master_name.sv
      /home/mendes/axi4_aib/axi4_aib_tools/rtl/axi_mm/axi_mm_master_top.sv
      /home/mendes/axi4_aib/axi4_aib_tools/rtl/axi_mm/axi_mm_slave_concat.sv
      /home/mendes/axi4_aib/axi4_aib_tools/rtl/axi_mm/axi_mm_slave_name.sv
      /home/mendes/axi4_aib/axi4_aib_tools/rtl/axi_mm/axi_mm_slave_top.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/behavior/clk_and2_cel.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/behavior/clk_and3_cel.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/behavior/clk_and4_cel.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/behavior/clk_buf_cel.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/behavior/clk_den_flop.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/behavior/clk_gate_cel.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/behavior/clk_inv_cel.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/behavior/clk_mux.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/behavior/clk_or2_cel.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/behavior/clk_or3_cel.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/behavior/clk_resize_cel.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/behavior/dmux_cell.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/dv/interface/dut_if_mac.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/dv/emib/emib_ch_m2s2.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/dv/emib/emib_m2s2.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/TXRX/en_logic_xxpad.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/PVTMON/flop.sv
      /home/mendes/axi4_aib/aib-protocols/common/rtl/level_delay.sv
      /home/mendes/axi4_aib/aib-protocols/llink/rtl/ll_auto_sync.sv
      /home/mendes/axi4_aib/aib-protocols/llink/rtl/ll_receive.sv
      /home/mendes/axi4_aib/aib-protocols/llink/rtl/ll_rx_ctrl.sv
      /home/mendes/axi4_aib/aib-protocols/llink/rtl/ll_rx_push.sv
      /home/mendes/axi4_aib/aib-protocols/llink/rtl/ll_transmit.sv
      /home/mendes/axi4_aib/aib-protocols/llink/rtl/ll_tx_cred.sv
      /home/mendes/axi4_aib/aib-protocols/llink/rtl/ll_tx_ctrl.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/PVTMON/mux2x1.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/TXRX/pad_out_logic.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aib_fsm/phase_adjust_fsm.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aib_fsm/phase_adjust_fsm_top.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aib_fsm/rcomp_calibration_fsm.v
      /home/mendes/axi4_aib/aib-protocols/common/rtl/rrarb.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aib_fsm/rx_offset_cal.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aib_fsm/rx_offset_cal_fsm_top.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/src/rtl/aib_fsm/rxoffset_top.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1.1/rtl/bca/ana_models/msv_models/TXRX/sampler.sv
      /home/mendes/axi4_aib/aib-protocols/common/rtl/syncfifo_mem1r1w.sv
      /home/mendes/axi4_aib/aib-protocols/common/rtl/syncfifo_ram.sv
      /home/mendes/axi4_aib/aib-protocols/common/rtl/syncfifo_reg.sv
      /home/mendes/axi4_aib/axi4_aib_tools/rtl/full_examples/aib_axi_top.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top aib_axi_top
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter linterFlow true
    rt::set_parameter synthReportEmptyAndUndriven false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-134394-616804/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
uplevel #0 { 
   $rt::db resetHdlParse
   set hsKey [rt::get_parameter helper_shm_key] 
   if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
      $rt::db killSynthHelper $hsKey
   } 
   source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
   return -code "error" $rt::result
 }
}
