# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-159268-616804/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a200tfbg676-2
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv {
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/rtl/aib_adapt_2doto.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/rtl/aib_adapt_rxchnl.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/rtl/aib_adapt_txchnl.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/rtl/aib_adaptrxdbi_rxdp.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/rtl/aib_adaptrxdp_async_fifo.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/rtl/aib_adaptrxdp_fifo.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/rtl/aib_adaptrxdp_fifo_ptr.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/rtl/aib_adaptrxdp_fifo_ram.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/rtl/aib_adapttxdbi_txdp.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/rtl/aib_adapttxdp_async_fifo.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/rtl/aib_adapttxdp_fifo.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/rtl/aib_adapttxdp_fifo_ptr.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/rtl/aib_adapttxdp_fifo_ram.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/rtl/aib_aliasd.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/rtl/aib_aux_channel.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/rtl/aib_avmm.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/rtl/aib_avmm_adapt_csr.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/rtl/aib_avmm_io_csr.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/rtl/aib_avmm_rdl_intf.sv
      /home/mendes/axi4_aib/axi4_aib_tools/rtl/interfaces/axi_if.v
      /home/mendes/axi4_aib/axi4_aib_tools/rtl/full_examples/axi_lite/aib_axi_bridge_master.v
      /home/mendes/axi4_aib/axi4_aib_tools/rtl/full_examples/axi_lite/aib_axi_bridge_slave.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/rtl/aib_bitsync.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/rtl/aib_bsr_red_wrap.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/rtl/aib_buffx1_top.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/rtl/aib_channel.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/rtl/aib_dcc.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/rtl/aib_io_buffer.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/rtl/aib_ioring.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/rtl/aib_jtag_bscan.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/rtl/aib_model_top.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/rtl/aib_mux21.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/rtl/aib_redundancy.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/rtl/aib_rstnsync.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/rtl/aib_sm.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/rtl/aib_sr_ms.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/rtl/aib_sr_sl.v
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/dv/emib/aliasv.sv
      /home/mendes/axi4_aib/aib-protocols/common/rtl/asyncfifo.sv
      /home/mendes/axi4_aib/aib-protocols/axi4-mm/axi_lite_a32_d32/axi_lite_a32_d32_master_concat.sv
      /home/mendes/axi4_aib/aib-protocols/axi4-mm/axi_lite_a32_d32/axi_lite_a32_d32_master_name.sv
      /home/mendes/axi4_aib/aib-protocols/axi4-mm/axi_lite_a32_d32/axi_lite_a32_d32_master_top.sv
      /home/mendes/axi4_aib/aib-protocols/axi4-mm/axi_lite_a32_d32/axi_lite_a32_d32_slave_concat.sv
      /home/mendes/axi4_aib/aib-protocols/axi4-mm/axi_lite_a32_d32/axi_lite_a32_d32_slave_name.sv
      /home/mendes/axi4_aib/aib-protocols/axi4-mm/axi_lite_a32_d32/axi_lite_a32_d32_slave_top.sv
      /home/mendes/axi4_aib/aib-protocols/ca/rtl/ca.sv
      /home/mendes/axi4_aib/aib-protocols/ca/rtl/ca_rx_align.sv
      /home/mendes/axi4_aib/aib-protocols/ca/rtl/ca_rx_align_fifo.sv
      /home/mendes/axi4_aib/aib-protocols/ca/rtl/ca_tx_mux.sv
      /home/mendes/axi4_aib/aib-protocols/ca/rtl/ca_tx_strb.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/rtl/dll.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/dv/emib/emib_ch_m2s2.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/dv/emib/emib_m2s2.sv
      /home/mendes/axi4_aib/aib-protocols/common/rtl/level_delay.sv
      /home/mendes/axi4_aib/aib-protocols/common/rtl/levelsync.sv
      /home/mendes/axi4_aib/aib-protocols/common/rtl/levelsync_sr.sv
      /home/mendes/axi4_aib/aib-protocols/llink/rtl/ll_auto_sync.sv
      /home/mendes/axi4_aib/aib-protocols/llink/rtl/ll_receive.sv
      /home/mendes/axi4_aib/aib-protocols/llink/rtl/ll_rx_ctrl.sv
      /home/mendes/axi4_aib/aib-protocols/llink/rtl/ll_rx_push.sv
      /home/mendes/axi4_aib/aib-protocols/llink/rtl/ll_transmit.sv
      /home/mendes/axi4_aib/aib-protocols/llink/rtl/ll_tx_cred.sv
      /home/mendes/axi4_aib/aib-protocols/llink/rtl/ll_tx_ctrl.sv
      /home/mendes/axi4_aib/aib-protocols/common/rtl/rrarb.sv
      /home/mendes/axi4_aib/aib-protocols/common/rtl/rst_regen_low.sv
      /home/mendes/axi4_aib/aib-protocols/common/rtl/syncfifo.sv
      /home/mendes/axi4_aib/aib-protocols/common/rtl/syncfifo_mem1r1w.sv
      /home/mendes/axi4_aib/aib-protocols/common/rtl/syncfifo_ram.sv
      /home/mendes/axi4_aib/aib-protocols/common/rtl/syncfifo_reg.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/dv/interface/avalon_mm_if.sv
      /home/mendes/axi4_aib/aib-phy-hardware/v2.0/rev1/dv/interface/dut_if_mac.sv
      /home/mendes/axi4_aib/axi4_aib_tools/rtl/full_examples/aib_axi_top.v
      /home/mendes/axi4_aib/axi4_aib_tools/rtl/full_examples/axi_lite/tb_aib_axi_bridge_master.v
      /home/mendes/axi4_aib/aib-protocols/axi4-mm/full_examples/common/axi_mm_csr.v
      /home/mendes/axi4_aib/aib-protocols/axi4-mm/full_examples/common/aximm_aib_top.v
      /home/mendes/axi4_aib/aib-protocols/axi4-mm/full_examples/common/aximm_follower_app.v
      /home/mendes/axi4_aib/aib-protocols/axi4-mm/full_examples/common/aximm_incr_gen.v
      /home/mendes/axi4_aib/aib-protocols/axi4-mm/full_examples/common/aximm_leader_app.v
      /home/mendes/axi4_aib/aib-protocols/axi4-mm/full_examples/common/aximm_rand_gen.v
      /home/mendes/axi4_aib/aib-protocols/axi4-mm/full_examples/common/aximm_wr_ctrl.v
      /home/mendes/axi4_aib/aib-protocols/axi4-mm/full_examples/common/mm_csr_ctrl.v
      /home/mendes/axi4_aib/aib-protocols/axi4-mm/full_examples/common/axi_mm_patchkr_top.v
      /home/mendes/axi4_aib/aib-protocols/axi4-mm/full_examples/common/axi_mm_patgen_top.v
      /home/mendes/axi4_aib/aib-protocols/axi4-mm/full_examples/common/aximm_d128_h2h_wrapper_top.v
      /home/mendes/axi4_aib/axi4_aib_tools/rtl/full_examples/axi_lite/aib_calib_slave_fsm.v
      /home/mendes/axi4_aib/axi4_aib_tools/rtl/full_examples/axi_lite/aib_calib_master_fsm.v
    }
      rt::read_verilog /home/mendes/axi4_aib/aib-protocols/axi4-mm/full_examples/common/jtag2avmm_bridge.v
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top top_aib_axi_bridge_master
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter linterFlow true
    rt::set_parameter synthReportEmptyAndUndriven false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-159268-616804/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
uplevel #0 { 
   $rt::db resetHdlParse
   set hsKey [rt::get_parameter helper_shm_key] 
   if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
      $rt::db killSynthHelper $hsKey
   } 
   source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
   return -code "error" $rt::result
 }
}
